In [53]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

                   
file = pd.read_excel('C:/Data_/excel/data_jobs_salary_all.xlsx',sheet_name='maaz_1')
file['job_posted_month']=file['job_posted_date'].dt.strftime('%b')
file['month_no']=pd.to_datetime(file['job_posted_date'],format='%b').dt.month
print(file)

                 job_title_short  \
0          Senior Data Scientist
1                  Data Engineer
2            Senior Data Analyst
3      Machine Learning Engineer
4                 Data Scientist
...                          ...
32667      Senior Data Scientist
32668               Data Analyst
32669             Data Scientist
32670               Data Analyst
32671             Data Scientist

                                               job_title     job_location  \
0      Senior Data Scientist Data and Analytics Perfo...   Bennington, NE
1                                     Data Engineer - MA         Mesa, AZ
2      Supervisory Information Technology Specialist ...   Alexandria, VA
3                    Machine Learning Research Scientist   Pittsburgh, PA
4                                    Data Scientist, AWS       Irving, TX
...                                                  ...              ...
32667                              Senior Data Scientist    Palo Alto, CA
32668  eCommerce Data Analyst | Hybrid Work | W2 Acce...       Austin, TX
32669    Clinical Data Visualization Specialist - Remote         Anywhere
32670                       Data Analyst/Report Writer 2       Austin, TX
32671  Data Science Product Manager - Recommendations...  Prague, Czechia

                job_via        job_schedule_type  job_work_from_home  \
0      via ZipRecruiter                Full-time               False
1            via Indeed                Full-time               False
2      via ZipRecruiter                Full-time               False
3       via Ai-Jobs.net                Full-time               False
4          via Snagajob  Full-time and Part-time               False
...                 ...                      ...                 ...
32667        via Indeed                Full-time               False
32668      via LinkedIn               Contractor               False
32669  via ZipRecruiter                Full-time                True
32670        via Adzuna                Full-time               False
32671   via Ai-Jobs.net                Full-time               False

                 search_location     job_posted_date  job_no_degree_mention  \
0                          Sudan 2023-04-24 09:51:15                  False
1                        Georgia 2023-03-13 12:51:23                   True
2        New York, United States 2023-07-05 07:03:38                   True
3        Illinois, United States 2023-04-13 16:05:41                  False
4           Texas, United States 2023-10-15 06:02:51                  False
...                          ...                 ...                    ...
32667  California, United States 2023-08-29 18:05:55                  False
32668       Texas, United States 2023-03-15 19:01:41                  False
32669  California, United States 2023-12-18 16:02:34                  False
32670       Texas, United States 2023-05-04 07:01:58                   True
32671                    Czechia 2023-03-31 20:02:52                  False

       job_health_insurance    job_country salary_rate  salary_year_avg  \
0                      True          Sudan        year         128050.0
1                      True  United States        year         140000.0
2                     False  United States        year         156000.0
3                      True  United States        year         140000.0
4                     False  United States        hour              NaN
...                     ...            ...         ...              ...
32667                  True  United States        year         191000.0
32668                 False  United States        hour              NaN
32669                  True  United States        hour              NaN
32670                 False  United States        hour              NaN
32671                 False        Czechia        year          89100.0

       salary_hour_avg                            company_name  \
0                  NaN                      Cox Communications
1                  NaN                           Worldgate LLC
2                  NaN  National Technical Information Service
3                  NaN                             Bosch Group
4            39.795002                          Presidio, Inc.
...                ...                                     ...
32667              NaN                                   Navan
32668        42.500000        TalentBurst, an Inc 5000 company
32669        55.000000                       Avispa Technology
32670        55.000000                                 My3Tech
32671              NaN                             Zeta Global

                                              job_skills job_posted_month  \
0      ['sql', 'python', 'aws', 'pyspark', 'tableau',...              Apr
1      ['sql', 'nosql', 'java', 'python', 'kafka', 's...              Mar
2                                                    NaN              Jul
3                              ['pytorch', 'tensorflow']              Apr
4      ['python', 'r', 'sql', 'c', 'aws', 'gcp', 'big...              Oct
...                                                  ...              ...
32667  ['go', 'python', 'sql', 'numpy', 'pandas', 'te...              Aug
32668                                ['python', 'excel']              Mar
32669                           ['sas', 'sas', 'python']              Dec
32670      ['sas', 'sas', 'word', 'excel', 'sharepoint']              May
32671                                                NaN              Mar

       month_no
0             4
1             3
2             7
3             4
4            10
...         ...
32667         8
32668         3
32669        12
32670         5
32671         3

[32672 rows x 18 columns]

In [54]:
file_salary=file[pd.notna(file['salary_year_avg'])][['salary_year_avg']]
file_salary
file_salary['salary_year_inflated by 1.03']=file_salary['salary_year_avg']*1.03
file_salary[['salary_year_avg','salary_year_inflated by 1.03']].head()

   salary_year_avg  salary_year_inflated by 1.03
0         128050.0                      131891.5
1         140000.0                      144200.0
2         156000.0                      160680.0
3         140000.0                      144200.0
6         135000.0                      139050.0

###Apply Fucntion

In [64]:
type(file)
file_1=file[file['salary_year_avg'].notna()][['job_title_short','salary_year_avg']]
file_1['salary_year_avg']=file_1.apply(lambda row:1.05*row['salary_year_avg'] if 'Senior' in row['job_title_short'] else 1.03*row['salary_year_avg'],axis=1)
file_1[['job_title_short','salary_year_avg']]

                 job_title_short  salary_year_avg
0          Senior Data Scientist         134452.5
1                  Data Engineer         144200.0
2            Senior Data Analyst         163800.0
3      Machine Learning Engineer         144200.0
6                  Data Engineer         139050.0
...                          ...              ...
32660      Senior Data Scientist         157500.0
32664               Data Analyst         200335.0
32666             Data Scientist         154500.0
32667      Senior Data Scientist         200550.0
32671             Data Scientist          91773.0

[22036 rows x 2 columns]

In [65]:
file['salary_year_avg'].head()

0    128050.0
1    140000.0
2    156000.0
3    140000.0
4         NaN
Name: salary_year_avg, dtype: float64